name: Bug
description: 缺陷（MCP）
title: "[Bug] "
labels:
  - bug
body:
  - type: dropdown
    id: severity
    attributes:
      label: 严重级别
      options:
        - P0
        - P1
        - P2
        - P3
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: 复现步骤
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期望结果
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 实际结果
    validations:
      required: true
  - type: input
    id: owner
    attributes:
      label: Owner
      placeholder: "@username"
    validations:
      required: true
  - type: input
    id: due
    attributes:
      label: 截止时间
      description: 例如 2026-02-01
    validations:
      required: false

